/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.seu.drivers.plugins;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.table.TableModel;

/**
 *
 * @author hp-6380
 */
public class MyProcessBar extends javax.swing.JPanel {

    private TableModel tableModel;
    /**
     * Creates new form MyProcessBar
     */
    public MyProcessBar(TableModel tableModel) {
        super();
        this.tableModel=tableModel;
        initComponents();
        //设置大小，得研究一下如何使组建能充满容器
        this.setSize(200,30);
        processBarLabel.setVisible(false);
        cancelButton.setVisible(false);
        resultNumLabel.setVisible(false);
//        this.setVisible(true);
    }
    
    public void setResultNumLabel(final String result){
        SwingUtilities.invokeLater(new Runnable(){
            @Override
            public void run() {
                resultNumLabel.setText(result);
            }
        });
    }
    
    public void startloadLabelChange(){
        SwingUtilities.invokeLater(new Runnable(){
            @Override
            public void run() {
                processBarLabel.setVisible(true);
                cancelButton.setVisible(true);
                resultNumLabel.setVisible(true);
//                cancelButton.setIcon(new ImageIcon(getClass().getResource("/edu/seu/lizhenglong/drivers/image/Cancel_16.png")));
//                processBarLabel.setIcon(new ImageIcon(getClass().getResource("/edu/seu/lizhenglong/drivers/image/processBar.gif")));
                resultNumLabel.setText("加载中...");
            }
        });
    }
    
    public void endLodaLabelChange(){
        SwingUtilities.invokeLater(new Runnable(){
            @Override
            public void run() {
                processBarLabel.setVisible(false);
                cancelButton.setVisible(false);
                resultNumLabel.setText("结果数量："+tableModel.getRowCount());
            }
        });
    }
    
    public void cancelLoadLabelChange(){
        SwingUtilities.invokeLater(new Runnable(){
            @Override
            public void run() {
                processBarLabel.setVisible(false);
                cancelButton.setVisible(false);
                resultNumLabel.setText("结果数量(中途取消）："+tableModel.getRowCount());
            }
        });
    }
    
    public void clearResultNumLabel(){
        SwingUtilities.invokeLater(new Runnable(){
            @Override
            public void run() {
                resultNumLabel.setText("结果数量：0");
            }
        });
    }
    
    private void initAction(){
        cancelButton.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                
            }
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        processBarLabel = new javax.swing.JLabel();
        resultNumLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(500, 22));

        processBarLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/seu/lizhenglong/drivers/image/processBar.gif"))); // NOI18N
        processBarLabel.setText(org.openide.util.NbBundle.getMessage(MyProcessBar.class, "MyProcessBar.processBarLabel.text")); // NOI18N

        resultNumLabel.setText(org.openide.util.NbBundle.getMessage(MyProcessBar.class, "MyProcessBar.resultNumLabel.text")); // NOI18N

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/seu/lizhenglong/drivers/image/Cancel_16.png"))); // NOI18N
        cancelButton.setText(org.openide.util.NbBundle.getMessage(MyProcessBar.class, "MyProcessBar.cancelButton.text")); // NOI18N
        cancelButton.setContentAreaFilled(false);
        cancelButton.setPreferredSize(new java.awt.Dimension(22, 22));
        cancelButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/seu/lizhenglong/drivers/image/cancel_16_red.png"))); // NOI18N
        cancelButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/seu/lizhenglong/drivers/image/cancel_16_red.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(processBarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultNumLabel)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(processBarLabel)
                    .addComponent(resultNumLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancelButton, resultNumLabel});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel processBarLabel;
    private javax.swing.JLabel resultNumLabel;
    // End of variables declaration//GEN-END:variables
}
