/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.seu.dataselector;

import edu.seu.dataselector2.CardPanel2;
import java.awt.BorderLayout;
import org.gephi.perspective.api.PerspectiveController;
import org.gephi.perspective.spi.Perspective;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//edu.seu.dataselector//DataSelector//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "DataSelectorTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true,roles={"auditSelector"})
@ActionID(category = "Window", id = "edu.seu.dataselector.DataSelectorTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "监控事件选择窗口",
        preferredID = "DataSelectorTopComponent"
)
@Messages({
    "CTL_DataSelectorAction=DataSelector",
    "CTL_DataSelectorTopComponent=DataSelector Window",
    "HINT_DataSelectorTopComponent=This is a DataSelector window"
})
public final class DataSelectorTopComponent extends TopComponent {

    private final CardPanel2 p;
    
    public DataSelectorTopComponent() {
        initLookAndFeel();
        initComponents();
        setName("监控事件选择窗口");
//        setToolTipText(Bundle.HINT_DataSelectorTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        
        p=CardPanel2.getInstance();
        this.add(p, BorderLayout.CENTER);
        
        //打开overview面板然后再转回此面板
        WindowManager.getDefault().invokeWhenUIReady(new Runnable(){
            @Override
            public void run() {
                PerspectiveController pc=Lookup.getDefault().lookup(PerspectiveController.class);
                
                for(Perspective p:pc.getPerspectives()){
                    if(p.getName().equals("overview")){
                        pc.selectPerspective(p);
                    }
                }
                for(Perspective p:pc.getPerspectives()){
                    if(p.getName().equals("auditSelector")){
                        pc.selectPerspective(p);
                    }
                }
                
            }
        });
        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    private void initLookAndFeel(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataSelectorTopComponent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
}
