/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.seu.dataselector;

import edu.seu.layout.LayoutImpl;
import edu.seu.networkbuild.api.BuildDiffNet;
import edu.seu.statistics.api.CalStatistics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import org.gephi.graph.api.GraphController;
import org.gephi.graph.api.GraphModel;
import org.gephi.utils.progress.ProgressTicket;
import org.gephi.utils.progress.ProgressTicketProvider;
import org.openide.util.Lookup;

/**
 *
 * @author hp-6380
 */
public class HomeIndex extends javax.swing.JPanel {

    private volatile static HomeIndex instance;
//    private DataSelectorTopComponent tp;
    private CardPanel tp;
    /**
     * Creates new form HomeIndex
     */
    private HomeIndex(CardPanel tp) {
        initComponents();
        initAction();
        this.tp=tp;
    }
    
    public static synchronized HomeIndex getInstance(CardPanel tp){
        if(instance==null){
            instance=new HomeIndex(tp);
        }
        return instance;
    }
    
    private void initAction(){
        
        keyword.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                tp.showPanel(Selector.KEY_SELECTOR);
            }
        });
        
        friend.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                tp.showPanel(Selector.FRIEND_SELECTOR);
            }
        });
        
        group.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                tp.showPanel(Selector.GROUP_SELECTOR);
            }
        });
        
        diff.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                new SwingWorker<Void,Void>(){
                    ProgressTicketProvider progressProvider = Lookup.getDefault().lookup(ProgressTicketProvider.class);
                    ProgressTicket ticket = null;
                    @Override
                    protected Void doInBackground() throws Exception {
                        if(progressProvider!=null){
                            ticket=progressProvider.createTicket("开始构建网络...", null);
                        }
                        
                        try{
                            BuildDiffNet diffBuilder=Lookup.getDefault().lookup(BuildDiffNet.class);
                            diffBuilder.build();
                            
                            ticket.setDisplayName("计算节点中心性参数...");
                            ticket.start(5);
                            ticket.progress(4);
                            CalStatistics calSta=Lookup.getDefault().lookup(CalStatistics.class);
                            calSta.execute();
                            
                            ticket.setDisplayName("网络节点布局...");
                            ticket.progress(4);
                            LayoutImpl layout=new LayoutImpl();
                            GraphModel graphModel=Lookup.getDefault().lookup(GraphController.class).getGraphModel();
                            layout.forceAtlasLayout2(graphModel);
                            ticket.finish("网络构建成功");
                            
                        }catch(Exception e){
                            e.printStackTrace();
                            ticket.finish();
                            JOptionPane.showMessageDialog(null, "构建消息传播网络中出现错误");
                        }
                        return null;
                    }
                    
                    @Override
                    protected void done(){
                       ticket.finish();
                    }
                }.execute();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        friend = new javax.swing.JButton();
        group = new javax.swing.JButton();
        keyword = new javax.swing.JButton();
        diff = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();

        friend.setFont(new java.awt.Font("方正姚体", 0, 48)); // NOI18N
        friend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/seu/dataselector/Brandnew/image/friend_48.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(friend, "关联人关系网"); // NOI18N

        group.setFont(new java.awt.Font("方正姚体", 0, 48)); // NOI18N
        group.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/seu/dataselector/Brandnew/image/group2_48.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(group, org.openide.util.NbBundle.getMessage(HomeIndex.class, "HomeIndex.group.text")); // NOI18N

        keyword.setFont(new java.awt.Font("方正姚体", 0, 48)); // NOI18N
        keyword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/seu/dataselector/Brandnew/image/chat_48.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(keyword, org.openide.util.NbBundle.getMessage(HomeIndex.class, "HomeIndex.keyword.text")); // NOI18N

        diff.setFont(new java.awt.Font("方正姚体", 0, 48)); // NOI18N
        diff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/seu/dataselector/Brandnew/image/diff3_48.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(diff, org.openide.util.NbBundle.getMessage(HomeIndex.class, "HomeIndex.diff.text")); // NOI18N

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jTextPane1.setText("点击进入关联人关系网数据操作界面，可以生成单个关联人的自中心网络或者多个关联人之间的关联关系网络。"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPane2.setEditable(false);
        jTextPane2.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane2.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jTextPane2.setText("点击进入群组管外网数据操作界面，可以生成单个群组的自中心网络或者多个群组之间的关联关系网"); // NOI18N
        jScrollPane2.setViewportView(jTextPane2);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPane3.setEditable(false);
        jTextPane3.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane3.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jTextPane3.setText("点击进入群组间消息传播网操作界面，此界面中可以选定特定关键词，生成该关键词在群成员和群组之间的发送接收关系网。"); // NOI18N
        jScrollPane3.setViewportView(jTextPane3);

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPane4.setEditable(false);
        jTextPane4.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane4.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jTextPane4.setText("单击直接生成消息传播概率路径网络。该网络是根据群聊消息以及群成员的转发行为推测得到的一个概率网络，网络中的边表示节点之间可能有消息传播行为，边权重为消息传播概率。"); // NOI18N
        jScrollPane4.setViewportView(jTextPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(friend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keyword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(group, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diff, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(friend, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(group, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(diff))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keyword)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {diff, friend, group, keyword});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton diff;
    private javax.swing.JButton friend;
    private javax.swing.JButton group;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JButton keyword;
    // End of variables declaration//GEN-END:variables
}
