/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.seu.dataselector;

import edu.seu.dataselector.oldPerspective.OldPerspective;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author hp-6380
 */
public class Selector extends javax.swing.JPanel {
    
    private static volatile Selector instance;
//    private DataSelectorTopComponent tp;
    private CardPanel tp;

    public static final String KEY_SELECTOR="KEY_SELECTOR";
    public static final String FRIEND_SELECTOR="FRIEND_SELECTOR";
    public static final String GROUP_SELECTOR="GROUP_SELECTOR";
    public static final String FRIEND_GROUP_RELATION="FRIEND_GROUP_RELATION";
    
    private KeySelector keySelector;
    private FriendSelector egoFriendSelector;
    private GroupSelector egoGroupSelector;
    private OldPerspective friendGroupPerspective;
    
    private CardLayout card=new CardLayout();
    /**
     * Creates new form Selector
     */
    private Selector(CardPanel tp) {
        try{
            initComponents();
            initAction();
            this.tp=tp;

            panel.setLayout(card);
            keySelector=KeySelector.getInstance();
            egoFriendSelector=FriendSelector.getInstance();
            egoGroupSelector=GroupSelector.getInstance();
            friendGroupPerspective=OldPerspective.getInstance();
            panel.add(keySelector);
            panel.add(egoFriendSelector);
            panel.add(egoGroupSelector);
            panel.add(friendGroupPerspective);

            card.addLayoutComponent(keySelector, KEY_SELECTOR);
            card.addLayoutComponent(egoFriendSelector, FRIEND_SELECTOR);
            card.addLayoutComponent(egoGroupSelector, GROUP_SELECTOR);
            card.addLayoutComponent(friendGroupPerspective, FRIEND_GROUP_RELATION);
            
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "selector 出错");
        }
            
    }
    
    public static synchronized Selector getInstance(CardPanel tp){
        if(instance==null){
            instance=new Selector(tp);
        }
        return instance;
    }
    
    private void initAction(){
        keyword.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                card.show(panel, KEY_SELECTOR);
            }
        });
        
        group.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                card.show(panel, GROUP_SELECTOR);
            }
        });
        
        friend.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                card.show(panel, FRIEND_SELECTOR);
            }
        });
        
        home.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                tp.showHomePage();
            }
        });
        
        group.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
               card.show(panel, FRIEND_GROUP_RELATION);
            }
        });
        
    }
    
    public void showPanel(String name){
        card.show(panel, name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        keyword = new javax.swing.JButton();
        group = new javax.swing.JButton();
        home = new javax.swing.JButton();
        friend = new javax.swing.JButton();

        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        keyword.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        keyword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/seu/dataselector/Brandnew/image/chat_16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(keyword, org.openide.util.NbBundle.getMessage(Selector.class, "Selector.keyword.text")); // NOI18N

        group.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        group.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/seu/dataselector/Brandnew/image/group_16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(group, org.openide.util.NbBundle.getMessage(Selector.class, "Selector.group.text")); // NOI18N

        home.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/seu/dataselector/Brandnew/image/home_16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(home, "主页"); // NOI18N

        friend.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        friend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/seu/dataselector/Brandnew/image/friend_16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(friend, org.openide.util.NbBundle.getMessage(Selector.class, "Selector.friend.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(friend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(group, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keyword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(372, 372, 372))
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyword)
                    .addComponent(group)
                    .addComponent(home)
                    .addComponent(friend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton friend;
    private javax.swing.JButton group;
    private javax.swing.JButton home;
    private javax.swing.JButton keyword;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
