/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.seu.dataselector2;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author hp-6380
 */
public class CardPanel2 extends javax.swing.JPanel {

    private static CardPanel2 instance;
    
    public static final String HOME_INDEX="HOME_INDEX";
    public static final String SELECTOR="SELECTOR";
    
    private Selector2 selector;
    private HomeIndex2 homeIndex;
    
    private CardLayout card=new CardLayout();
    /**
     * Creates new form Test
     */
    private CardPanel2() {
        initComponents();
        initMyComponents();
    }
    
    public static synchronized CardPanel2 getInstance(){
        if(instance==null){
            instance=new CardPanel2();
        }
        return instance;
    }
    
    
    private void initMyComponents(){
        try{
            System.out.println(Thread.currentThread().getName());
            this.setLayout(card);
            selector=Selector2.getInstance(this);
            homeIndex=HomeIndex2.getInstance(this);
            this.add(selector);
            this.add(homeIndex);
            card.addLayoutComponent(selector, SELECTOR);
            card.addLayoutComponent(homeIndex, HOME_INDEX);
            card.show(this, HOME_INDEX);    
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "chuchuo");
        }
        
    }
    
    public void showPanel(String name){
        card.show(this, SELECTOR);
        selector.showPanel(name);
        selector.setSelectedButton(name);
    }
    
    public void showHomePage(){
        card.show(this, HOME_INDEX);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setForeground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
